project/config/routes.rb
Rails.application.routes.draw do
  resources :associations do
  		resources :user
  	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#home"
end

project/app/models/association.rb
class Association < ApplicationRecord
	has_many :users	
end

project/app/models/user.rb
class User < ApplicationRecord
	belongs_to :association
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success, :danger
end

project/app/controllers/associations_controller.rb
class AssociationsController < ApplicationController
  before_action :set_association, only: [:show, :edit, :update, :destroy]

  # GET /associations
  # GET /associations.json
  def index
    @associations = Association.all
  end

  # GET /associations/1
  # GET /associations/1.json
  def show
  end

  # GET /associations/new
  def new
    @association = Association.new
  end

  # GET /associations/1/edit
  def edit
  end

  # POST /associations
  # POST /associations.json
  def create
    @association = Association.new(association_params)

    respond_to do |format|
      if @association.save
        format.html { redirect_to @association, success: 'Association was successfully created.' }
        format.json { render :show, status: :created, location: @association }
      else
        format.html { render :new }
        format.json { render json: @association.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associations/1
  # PATCH/PUT /associations/1.json
  def update
    respond_to do |format|
      if @association.update(association_params)
        format.html { redirect_to association_path(@association.id), success: 'Association was successfully updated.' }
        format.json { render :show, status: :ok, location: @association }
      else
        format.html { render :edit }
        format.json { render json: @association.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associations/1
  # DELETE /associations/1.json
  def destroy
    @association.destroy
    respond_to do |format|
      format.html { redirect_to associations_url, notice: 'Association was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_association
      @association = Association.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def association_params
      params.require(:association).permit(:name)
    end
end

project/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home

	end
end

project/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_association
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, success: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, success: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, danger: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_association
      @association = Association.find_by_id(params[:id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :admin)
    end
end

project/app/helpers/users_helper.rb
module UsersHelper
end

project/app/views/associations/edit.html.erb
<h1>Éditer Association</h1>

<%= render 'form', association: @association %>

<p class="btn btn-primary"> 
	<%= link_to 'Voir', @association %>
</p>
<p class="btn btn-default">
	<%= link_to 'Annuler', @association %>
</p>

project/app/views/associations/index.html.erb
<h1 class="text-center">Associations</h1>

<table class="table">
  <thead>
    <tr><th>Nom</th></tr>
  </thead>
  <tbody>
    <% @associations.each do |association| %>
      <tr>
        <td><strong><%= association.name %></strong></td>
        <td><%= link_to 'Voir', association, class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Éditer', edit_association_path(association), 
              class: 'btn btn-default btn-sm' %></td>
        <td><%= link_to 'Supprimer', association, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouvelle Association', new_association_path %>

project/app/views/associations/new.html.erb
<h1 class="text-center">Créer une Association</h1>

<%= render 'form', association: @association %>

<%= link_to 'Retour', associations_path %>

project/app/views/associations/show.html.erb
<p class="text-center">
  <strong style="font-size: 2em"><%= @association.name %></strong>
</p>

<p class="btn btn-success btn-sm"> 
	<%= link_to 'Éditer', edit_association_path(@association) %>
</p>
<p class="btn btn-default btn-sm">
	<%= link_to 'Retour', associations_path %>
</p>
<p class="btn btn-default btn-sm">
	<%= link_to 'Voir membres', users_path %>
</p>

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </head>

  <body>
  	<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Ruby On Rails</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= associations_path %>">Association</a>
          </li>
        </ul>
      </div>
    </nav>
   	<div class="container" style="padding-top: 5rem">
   		<% if flash[:success] %>
    	   <div class="alert alert-success">
           <%= flash[:success] %>
         </div>
      	<% end %>
    	<%= yield %>
    </div>
  </body>
</html>

project/app/views/pages/home.html.erb
<h1 class="text-center" style="border-bottom: solid"> Bienvenue !</h1>

<p style="text-align: center; margin-top: 10em"> 
	<img src="/home.png" alt="Maison" class="img-responsive">
</p>

project/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

project/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Membres</h1>

<table class="table" style="margin-top: 3em">
  <thead>
    <tr>
      <th>Prénom</th>
      <th>Nom</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td>
          <% if user.admin %>
            <p>Oui</p>
          <% end %>
        </td>
        <td><%= link_to 'Voir', user, class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Éditer', edit_user_path(user), 
                class: 'btn btn-default btn-sm' %></td>
        <td><%= link_to 'Supprimer', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouveau Membre', new_user_path %>

project/app/views/users/new.html.erb
<h1 class="text-center">Nouveau membre</h1>

<%= render 'form', user: @user %>

<%= link_to 'Retour', users_path %>

project/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>